name: "HCL AppScan CodeSweep Publish"
on:
  workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish issues to ASoC
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          publish_on_merge: true
          application_id: 246455ca-eba5-4b41-939c-bad4e9e3fcb0
          status: failure
          fetch-depth: 0
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
